#!/usr/bin/env bash

LIBDIR='/var/lib/cryptochat'

checks() {
	if [ -z $(which node) ]; then
		printf "node isn't installed.\nyou can easily acquire it using https://github.com/nvm-sh/nvm.\n"
		exit 1;
	elif [[ ! -d "$LIBDIR" ]]; then
		printf "%s doesn't exist. did you install using the makefile?" "$LIBDIR" 
		exit 1;
	fi
}

run() {
	(
	cd "${LIBDIR}" || exit "${?}"
	source ./.env || exit "${?}"
	node ./cli.js || exit "${?}"
	)
}
checks || exit "${?}"
run
